### ISSUE TITLE
An urgent request.

### ISSUE THREAD

**Issue by ASMlRP** [Aterfax/Node.js-DCS-WebGCI#17]
Hello, Sir. I have successfully connected Tacview and Cesium, but currently, I am unable to view the ACMI file on Cesium. Could you please help me understand the issue? Thank you!

**Comment by Aterfax** [comment]
This project doesn't save ACMI history nor can it show ACMI from files. It connects to a tacview socket and can only show a live stream.

Without log output I cannot suggest a cause of any issues.

**Comment by Aterfax** [comment]
If you want a live map from a server via Tacview I would recommend using https://github.com/Aterfax/sneaker as I have mostly abandoned doing this project.

**Comment by ASMlRP** [comment]
Hello sir, I would like to connect the flight simulation feature of Tacview to the Earth in Cesium, allowing my ACMI files to be played in Tacview and displayed on the Cesium website, similar to what you have showcased in this project.

**Comment by ASMlRP** [comment]
I can definitely provide you with some technical guidance for your flight simulation project. However, I am an AI language model and cannot directly contact you via email. But don't worry, we can continue the discussion here. Please feel free to ask any specific questions you have, and I'll do my best to assist you.

**Comment by ASMlRP** [comment]
Hello sir, I would like to connect the flight simulation feature of Tacview to the Earth in Cesium, allowing my ACMI files to be played in Tacview and displayed on the Cesium website, similar to what you have showcased in this project.

**Comment by ASMlRP** [comment]
I am an avid enthusiast of flight simulators, but when it comes to the operation and development of projects, I'm completely clueless. I would be immensely grateful if you could provide me with some technical guidance. If possible, could we exchange contact information via email? Thank you.

**Comment by Aterfax** [comment]
Given you intially posted a comment with the following content and then deleted it:

> I can definitely provide you with some technical guidance for your flight simulation project. However, I am an AI language model and cannot directly contact you via email. But don't worry, we can continue the discussion here. Please feel free to ask any specific questions you have, and I'll do my best to assist you.

This looks like spam so I am closing.
